components/faucet-claim.tsx, components/faucet-success.tsx, components/faucet.tsx, components/free-pass.tsx, lib/constants.ts
this PR aims to fix deployements and update OG/free pass to farmer pass
=> 🐛  fix staging + farmer pass

app/layout.tsx, components/notify-banner.tsx
this pr aims to add the banner indicating the faucet has had changes
=> :sparkles: new faucet banner

__tests__/components/__snapshots__/faucet-claim.test.tsx.snap, __tests__/components/faucet-claim.test.tsx, __tests__/pages/__snapshots__/faucet.test.tsx.snap, __tests__/pages/faucet.test.tsx, __tests__/pages/home.test.tsx, components/faucet-claim.tsx
this pr aims to add new tests + support for downtime screen
=> 🚧 scheduled downtime

components/faucet-claim.tsx
this pr aims to revert downtime!
=> :coffin: revert downtime

components/faucet-claim.tsx
this pr aims to schedule downtime!
=> :bug: simulate downtime

components/faucet-claim.tsx
=> :pencil2: fix typo

app/rate-limit/page.tsx
this pr aims to update copy for `/rate-limit`
=> :pencil2: update copy for rate limit

components/faucet-claim.tsx
this pr aims to update time to 15 seconds
=> :pencil2: update time to 15s

app/faucet/page.tsx, components/faucet-claim.tsx, lib/types.ts
this pr aims to add functionality to limit claims by only allowing users with `0.001` mainnet ETH to claim funds
=> 👽 limit claims

components/faucet-claim.tsx, components/notify-banner.tsx
this pr aims to add the updated mainnet eth requirement + new banner
=> ✨ mainnet ETH requirement

app/layout.tsx, components/faucet-claim.tsx, components/navbar.tsx, components/ui/dropdown-menu.tsx, components/wallet-details.tsx, lib/constants.ts, package-lock.json, package.json
this pr aims to add dropdown navbar support
=> ✨ dropdown navbar

app/layout.tsx, components/notify-banner.tsx
this pr aims to fix the notify banner
=> :bug: fix margin

app/faucet/page.tsx, app/rate-limit/page.tsx, components/carrot-container.tsx, components/faucet-claim.tsx, components/info-carrot.tsx, components/notify-banner.tsx, components/token-tabs.tsx, lib/types.ts
this pr aims to break down cooldown periods across tokens
=> ✨ individual cooldown periods

README.md
=> broken faucet link

lib/thirdweb-client.ts
this pr aims to auto switch wallet to starknet sepolia
=> :sparkles: add starknet sepoiia

app/api/spirit-karrot/route.tsx, app/spirit-karrot/[slug]/page.tsx, app/spirit-karrot/page.tsx, components/client-redirect.tsx
this pr aims to update the og image flow
now twitter sharing URLs will be `/spirit-karrot/<karrot_name>` 
for example -> `/spirit-karrot/kelon` or `/spirit-karrot/kazzar` 
and all these will redirect to `/spirit-karrot`
=> ✨ og image flow

app/spirit-karrot/page.tsx
this pr aims to fix the bug in prod
=> fix: make spirit karrot link lower case

app/spirit-karrot/[slug]/page.tsx, app/spirit-karrot/page.tsx
this pr aims to fix the no wallet bugs
=> :bug: fix no wallet state

app/spirit-karrot/page.tsx
this pr aims to fix non-null safe `toLowerCase`
=> 🚑 type safety

queries/useFaucetStats.ts, queries/useSpiritKarrot.ts
this pr aims to increase polling duration on faucet
=> :alien: update polling intervals

app/faucet/page.tsx, components/faucet-claim.tsx
=> :bug: downtime

app/spirit-karrot/page.tsx
this pr aims to add downtime to `spirit-karrot`
=> :bug: spirit karrot downtime

app/faucet/page.tsx, app/spirit-karrot/page.tsx, components/faucet-claim.tsx
Reverts kkrt-labs/faucet-frontend#95
=> Revert ":bug: downtime"

app/faucet/page.tsx, app/spirit-karrot/page.tsx, components/faucet-claim.tsx
Reverts kkrt-labs/faucet-frontend#96
=> Revert "Revert ":bug: downtime""

app/faucet/page.tsx, app/spirit-karrot/page.tsx, components/faucet-claim.tsx, queries/useFaucetStats.ts, queries/useSpiritKarrot.ts
this pr aims to remove the polling on `useFaucetStats` and `useSpiritKarrot`
=> 🔥 remove query polling

app/faucet/page.tsx, components/faucet-claim.tsx, components/spirit-karrot-modal.tsx, components/token-tabs.tsx, hooks/useFaucet.ts, lib/constants.ts, queries/useFaucetBalance.ts, queries/useFaucetStats.ts
this pr aims to fix and segregate contract calls of backend and frontend
=> :bug: refetch + dev/prod

components/faucet-claim.tsx
this pr aims to fix copy for different states of the claim button
=> :pencil2: fix copy for different states

app/spirit-karrot/page.tsx
this pr aims to add back no wallet state on spirit karrot page
=> :recycle: no wallet state

README.md
=> Typo correction README.md
